<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Property;
use App\Models\User;
use App\Models\Category;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $userIds = User::pluck('id')->toArray();
        $categoryIds = Category::pluck('id')->toArray();
        if (empty($userIds) || empty($categoryIds)) return;

        $properties = [
            [
                'title' => 'Luxury 3BHK Family House',
                'description' => 'A spacious house with a modern kitchen and large backyard.',
                'type' => 'house',
                'price' => 45000,
                'price_period' => 'month',
                'location' => 'Bandra West, Mumbai',
                'address' => 'Pali Hill, Bandra West',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area_sqft' => 1500,
                'furnishing' => 'semi-furnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
            [
                'title' => 'Prime Corner Retail Shop',
                'description' => 'Ideal for a showroom or boutique in a busy commercial area.',
                'type' => 'shop',
                'price' => 120000,
                'price_period' => 'month',
                'location' => 'Andheri West, Mumbai',
                'address' => 'Link Road, Andheri',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'area_sqft' => 800,
                'furnishing' => 'unfurnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
            [
                'title' => 'Cozy 1BHK House near Station',
                'description' => 'Compact and affordable house for working professionals.',
                'type' => 'house',
                'price' => 15000,
                'price_period' => 'month',
                'location' => 'Borivali, Mumbai',
                'address' => 'Station Road',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area_sqft' => 450,
                'furnishing' => 'semi-furnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
            [
                'title' => 'Grand 5BHK Independent House',
                'description' => 'A massive property with multiple floors and private parking.',
                'type' => 'house',
                'price' => 250000,
                'price_period' => 'month',
                'location' => 'Juhu, Mumbai',
                'address' => 'Juhu Tara Road',
                'bedrooms' => 5,
                'bathrooms' => 5,
                'area_sqft' => 3500,
                'furnishing' => 'fully-furnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
            [
                'title' => 'Small Boutique Shop Space',
                'description' => 'Perfect for a small business or startup gallery.',
                'type' => 'shop',
                'price' => 30000,
                'price_period' => 'month',
                'location' => 'Powai, Mumbai',
                'address' => 'Hiranandani Gardens',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'area_sqft' => 300,
                'furnishing' => 'unfurnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
            [
                'title' => 'Standard 2BHK Suburban House',
                'description' => 'Quiet location with plenty of sunlight and fresh air.',
                'type' => 'house',
                'price' => 25000,
                'price_period' => 'month',
                'location' => 'Thane West',
                'address' => 'Ghodbunder Road',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'area_sqft' => 950,
                'furnishing' => 'unfurnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
            [
                'title' => 'Main Road Facing Commercial Shop',
                'description' => 'High visibility and great foot traffic for any retail venture.',
                'type' => 'shop',
                'price' => 85000,
                'price_period' => 'month',
                'location' => 'Worli, Mumbai',
                'address' => 'Annie Besant Road',
                'bedrooms' => 0,
                'bathrooms' => 1,
                'area_sqft' => 600,
                'furnishing' => 'semi-furnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
            [
                'title' => 'Elegant Row House with Terrace',
                'description' => 'Exclusive row house with a large open terrace and garden.',
                'type' => 'house',
                'price' => 75000,
                'price_period' => 'month',
                'location' => 'Vashi, Navi Mumbai',
                'address' => 'Sector 17',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'area_sqft' => 1800,
                'furnishing' => 'semi-furnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
            [
                'title' => 'Modern Office/Shop Cabin',
                'description' => 'Fully air-conditioned cabin space for professional work.',
                'type' => 'shop',
                'price' => 20000,
                'price_period' => 'month',
                'location' => 'Goregaon East, Mumbai',
                'address' => 'Film City Road',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'area_sqft' => 250,
                'furnishing' => 'fully-furnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
            [
                'title' => 'Spacious 4BHK Bunglow',
                'description' => 'Bunglow with premium fittings and 24/7 security.',
                'type' => 'house',
                'price' => 180000,
                'price_period' => 'month',
                'location' => 'Chembur, Mumbai',
                'address' => 'Diamond Garden',
                'bedrooms' => 4,
                'bathrooms' => 4,
                'area_sqft' => 2800,
                'furnishing' => 'semi-furnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
            [
                'title' => 'Clothing Boutique Shop',
                'description' => 'Ready to move in with shelves and lighting installed.',
                'type' => 'shop',
                'price' => 55000,
                'price_period' => 'month',
                'location' => 'Colaba, Mumbai',
                'address' => 'Causeway',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'area_sqft' => 400,
                'furnishing' => 'fully-furnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
            [
                'title' => 'Renovated 1BHK Attic House',
                'description' => 'Unique attic-style house with vintage charm.',
                'type' => 'house',
                'price' => 40000,
                'price_period' => 'month',
                'location' => 'Bandra West, Mumbai',
                'address' => 'Chapel Road',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area_sqft' => 600,
                'furnishing' => 'fully-furnished',
                'status' => 'approved',
                'is_featured' => true,
            ],
        ];

        foreach ($properties as $data) {
            $data['user_id'] = $userIds[array_rand($userIds)];
            $data['category_id'] = $categoryIds[array_rand($categoryIds)];
            Property::create($data);
        }
    }
}
